# Generated by Django 3.2.5 on 2021-07-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
