# Generated by Django 3.2.5 on 2021-07-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_alter_solve_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='time',
            field=models.IntegerField(),
        ),
    ]
