# Generated by Django 3.2.5 on 2021-07-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0004_auto_20210725_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mo3', models.IntegerField()),
                ('ao5', models.IntegerField()),
                ('ao12', models.IntegerField()),
                ('single', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pb_single', to='timer.solve')),
            ],
        ),
    ]
