# Generated by Django 3.2.5 on 2021-07-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0005_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='ao12',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='ao5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='mo3',
            field=models.IntegerField(null=True),
        ),
    ]
