# Generated by Django 3.2.5 on 2021-07-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0006_auto_20210729_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='mo3',
        ),
    ]
