# Generated by Django 3.2.5 on 2021-08-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0008_auto_20210729_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='single_proper',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='single',
            field=models.IntegerField(),
        ),
    ]
